### ISSUE TITLE
Conga 5090

### ISSUE THREAD

**Issue by DarthDestroyer** [txitxo0/valetudo-addon#10]
Hey Guys!

Awesome works so far! Thank you very much for all of this!

The "rooting" works with 3x90, 4090 & 5490: @3I#sc$RD%xm^2S&2

I've also added everything to the hosts file, but i cant get it to work with HA! Its stuck at "loading state" and the log doesnt seem to say too much.

I would love to submit more Informations, if needed!

Kind Regards

**Comment by txitxo0** [comment]
Hi! Could you show us your hosts file? 

(For better a chat up, you can find us under the grupo @freeconga in telegram https://t.me/freeconga)

**Comment by DarthDestroyer** [comment]
```
127.0.0.1 localhost

::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.86.9 cecotec.das.3irobotix.net cecotec.download.3irobotix.net cecotec.log.3irobotix.net cecotec.ota.3irobotix.net eu.das.3irobotics.net eu.log.3irobotics.net eu.ota.3irobotics.net
```

**Comment by txitxo0** [comment]
There is no support for this conga yet due to this robot use SSL encryption protocol. Sorry

**Comment by txitxo0** [comment]
For 5090 and 5490 test with this pack of hosts

cecotec-das.3irobotix.net cecotec-log.3irobotix.net cecotec-upgrade.3irobotix.net cecotec-download.3irobotix.net
