### ISSUE TITLE
No segments after a persistant data reset | Conga 3390

### ISSUE THREAD

**Issue by Pabsilon** [txitxo0/valetudo-addon#11]
Hi, 

First of all, great addon! Thanks for breaking the chains of the terrible, terrible app!

Because of a slippery carpet, I had to reset the map with the 0.1.4 or 0.1.5 version of the addon (when it was the current one) and the map was generated without segments. I've tried a couple of times now.
As of 0.1.6, the map is still generated without a single segment, and since in order to create segments you split smaller segments... it can't be done: You need to select exactly one segment to execute a split! 

I'm using a Conga 3390.

If you need any kind of log, I'd be happy to test whatever is needed

**Comment by txitxo0** [comment]
Mmmm I can't help a lot with segments (mine doesn't have segments) let's wait till someone more useful would be able to check

@adrigzr

**Comment by adrigzr** [comment]
This could be related with added support for pending map handler of Valetudo ([commit](https://github.com/Hypfer/Valetudo/commit/ed0455d66a46b7adc16e91d34daff2da3e784417)). Till they add full support for this I think this will be broken.
