### ISSUE TITLE
Add support for Conga 7090

### ISSUE THREAD

**Issue by triplecillas** [txitxo0/valetudo-addon#17]
I want to integrate my Conga 7090 with Home Assistant using Valetudo Add-on.
As far as I know, this is a not supported model currentely.
In any case I want to try and help, if possible, to add this model to the list of supported models.
Following the steps provided in the documentation of the add-on, I reach the step of "Access your Conga through SSH" but I cannot find the USB port in the robot.
Does anyone know where it is located?

**Comment by txitxo0** [comment]
Did you try directly over ssh (the other way to get the robot rooted?

**Comment by triplecillas** [comment]
No, because it indicates that it is not a recommended method.
Should I try it? What is the disadvantage or danger of this second method so that it is not recommended?
I don't want to put the integrity of my Conga at risk.

**Comment by txitxo0** [comment]
If you hace already connected your conga through the official cecotec app, your conga is already connected to you wifi, so then... The integrity the ssh method says is already 'broken'. 

In fact, almost everybody uses this way, it is easier and more comfortable 'over the air' 

Anyway, I don't know if the password we shared in the docs will be valid for your conga... Who knows?, the best approach is try and test :)

**Comment by triplecillas** [comment]
OK understood. Thank you.
I am going to test and hope the password is valid.
I will update asap.

**Comment by triplecillas** [comment]
Unfortunately it doesn't work.
Neither of the two passwords is valid.
Any chance to move on?
Any guide on how to get the password?
Any help is welcome.

**Comment by txitxo0** [comment]
I don't know...bur que can mover this discussion to this other repo, and Cross fingers thinking that the developer knows what to do...

 https://github.com/adrigzr/agnoc/issues

**Comment by triplecillas** [comment]
Ok, good idea.
But how does the discussion move to the other repo? (I am new to github)
Or by "move", do you mean open a new issue there?

**Comment by txitxo0** [comment]
Yep, open a new one in there ;)
